In [4]:
from keras.models import load_model
import numpy as np
import tensorflow.keras.preprocessing.image
import tensorflow as tf

In [6]:
model = load_model('model.h5')
print('Model Loaded Succesuflly')

Model Loaded Succesuflly


In [ ]:
def classify(img_file):
    img_name = img_file
    test_image = tensorflow.keras.preprocessing.image.load_img(img_name, target_size = (256, 256),grayscale=True)

    test_image = tensorflow.keras.preprocessing.image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis=0)
    result = model.predict(test_image)
    arr = np.array(result[0])
    print(arr)
    maxx = np.amax(arr)
    max_prob = arr.argmax(axis=0)
    max_prob = max_prob + 1
    classes=["NONE", "ONE", "TWO", "THREE", "FOUR", "FIVE"]
    result = classes[max_prob - 1]
    print(img_name,result)


import os
path =  'F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/'
files = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.png' in file:
            files.append(os.path.join(r, file))
            print(os.path.join(r, file))


for f in files:
    classify(f)
    print('\n')

F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_0.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_1.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_10.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_100.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_101.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_102.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_103.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_104.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_105.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_106.png
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_107.png
F:/D

C:\Users\HP.DESKTOP-5IHNLMQ\anaconda3\lib\site-packages\keras\utils\image_utils.py:409: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn(


1/1 [==============================] - 1s 601ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_0.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_1.png NONE


1/1 [==============================] - 0s 100ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_10.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_100.png NONE


1/1 [==============================] - 0s 104ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_101.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\F

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_141.png NONE


1/1 [==============================] - 0s 107ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_142.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_143.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_144.png NONE


1/1 [==============================] - 0s 102ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_145.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIV

1/1 [==============================] - 0s 133ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_185.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_186.png NONE


1/1 [==============================] - 0s 87ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_187.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_188.png NONE


1/1 [==============================] - 0s 102ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_189.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FI

1/1 [==============================] - 0s 158ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_228.png NONE


1/1 [==============================] - 0s 111ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_229.png NONE


1/1 [==============================] - 0s 101ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_23.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_230.png NONE


1/1 [==============================] - 0s 107ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_231.png NONE


1/1 [==============================] - 0s 100ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/F

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_271.png NONE


1/1 [==============================] - 0s 104ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_272.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_273.png NONE


1/1 [==============================] - 0s 100ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_274.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_275.png NONE


1/1 [==============================] - 0s 99ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIV

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_314.png NONE


1/1 [==============================] - 0s 101ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_315.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_316.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_317.png NONE


1/1 [==============================] - 0s 96ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_318.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FI

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_358.png NONE


1/1 [==============================] - 0s 103ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_359.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_36.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_360.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_361.png NONE


1/1 [==============================] - 0s 98ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\

1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_400.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_401.png NONE


1/1 [==============================] - 0s 105ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_402.png NONE


1/1 [==============================] - 0s 103ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_403.png NONE


1/1 [==============================] - 0s 126ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_404.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/

1/1 [==============================] - 0s 99ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_444.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_445.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_446.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_447.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_448.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_488.png NONE


1/1 [==============================] - 0s 96ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_489.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_49.png NONE


1/1 [==============================] - 0s 111ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_490.png NONE


1/1 [==============================] - 0s 108ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_491.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIV

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_530.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_531.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_532.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_533.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_534.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIV

1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_574.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_575.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_576.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_577.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_578.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test

1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_72.png NONE


1/1 [==============================] - 0s 125ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_73.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_74.png NONE


1/1 [==============================] - 0s 109ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_75.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIVE_76.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FIVE\FIV

1/1 [==============================] - 0s 126ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_113.png ONE


1/1 [==============================] - 0s 153ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_114.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_115.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_116.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_117.png ONE


1/1 [==============================] - 0s 109ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FO

1/1 [==============================] - 0s 99ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_157.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_158.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_159.png NONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_16.png ONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_160.png NONE


1/1 [==============================] - 0s 94ms/step
[1. 0. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FO

1/1 [==============================] - 0s 109ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_20.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_200.png ONE


1/1 [==============================] - 0s 141ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_201.png ONE


1/1 [==============================] - 0s 141ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_202.png ONE


1/1 [==============================] - 0s 109ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_203.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FO

1/1 [==============================] - 0s 109ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_242.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_243.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_244.png ONE


1/1 [==============================] - 0s 125ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_245.png ONE


1/1 [==============================] - 0s 158ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_246.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FO

1/1 [==============================] - 0s 125ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_286.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_287.png ONE


1/1 [==============================] - 0s 109ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_288.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_289.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_29.png ONE


1/1 [==============================] - 0s 125ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOU

[6.119911e-35 1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_326.png ONE


1/1 [==============================] - 0s 94ms/step
[4.0514414e-26 1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_327.png ONE


1/1 [==============================] - 0s 94ms/step
[6.900345e-16 1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_328.png ONE


1/1 [==============================] - 0s 109ms/step
[1.3234896e-18 1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 13/HandGestureDataset/test/FOUR\FOUR_329.png ONE


1/1 [==============================] - 0s 94ms/step
[0. 1. 0. 0. 0. 0.]
F:/Data/Dinesh , Yantraveda/Campus X/AI/Day - 1